### ISSUE TITLE
Issue with Xalan extension

### ISSUE THREAD

**Issue by Teutron-flo** [SingingBush/barcode4j#47]
Hi,
sorry for the stupid question, but is it maybe possible that you forgot to release the xalan extension package (artifactId barcode4j-xalan)?
Because right now I try to migrate from Barcode4J 2.1 to your version and still after a lot of changes I get:

```
file:/simple_test.xsl; Line #31; Column #64; java.lang.NoSuchMethodException: For extension function, could not find method org.apache.xml.dtm.ref.DTMNodeIterator.generate([ExpressionContext,] #STRING).
2024-03-05 16:29:53,501 [FATAL] [de.fop.generator.LogEventListener] [0000]: "fo:instream-foreign-object" is missing child elements. Required content model: one (1) non-XSL namespace child (No context info available)
(Location of error unknown)org.apache.fop.fo.ValidationException: "fo:instream-foreign-object" is missing child elements. Required content model: one (1) non-XSL namespace child (No context info available)
```

Thanks & BR
Florian

**Comment by Teutron-flo** [comment]
I made a last local test to verify my assumption and it looks correct.
After creating my own local barcode4j-xalan, with your code:
		<dependency>
			<groupId>com.singingbush</groupId>
			<artifactId>barcode4j-xalan</artifactId>
			<version>2.2.2-test</version>
		</dependency>

The error disappear and I get the barcodes displayed.

**Comment by SingingBush** [comment]
that's interesting, I didn't publish _barcode4j-xalan_ as there is no _net.sf.barcode4j:barcode4j-xalan_ in maven central. I suspect their published jars were in fact from the Ant build and the xjc & xalan code was bundled into the barcode4j jar. I've pushed a change to main now to do the same via maven. Please pull main and do another build. If it resolves the issue for you I can publish a new release today.

**Comment by Teutron-flo** [comment]
Hi, 

sorry for my late response here, but I had a day off on Friday and that's why not the time to check the same.

To point 1. I tried it with adding only 
        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
        </dependency>
into my pom, but this doesn't solve the issue here.

To point 2. I tried to build the barcode4j project local, but I have to say again sorry, but it looks like I'm to dump for it :)
Because that moves my maven into a local error generator :).
If you can explain it in 2-3 sentences how to build it, I can check it again.

BR
Florian

**Comment by SingingBush** [comment]
just pull the latest changes in the main branch of this repo and run `mvn clean install` in the root directory of the project. That will put *2.2.3-SNAPSHOT* into your local mvn repo, then you can set the dependencies of your project to use the snapshot build, eg:

```xml
    <dependency>
        <groupId>com.singingbush</groupId>
        <artifactId>barcode4j</artifactId>
        <version>2.2.3-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>com.singingbush</groupId>
        <artifactId>barcode4j-fop-ext</artifactId>
        <version>2.2.3-SNAPSHOT</version>
    </dependency>
```

**Comment by SingingBush** [comment]
I've deployed  a snapshot build to maven central now so there's no need to do a local build/install. Just enable snapshots in your m2 settings and use `2.2.3-SNAPSHOT` in your project. Let me know how it goes.

**Comment by SingingBush** [comment]
great, thanks for the confirmation. I'm releasing 2.2.3 to maven central now. (usually available within a couple of hours)
